#!/usr/bin/env bash
#Script to install and configure nginx on the server

sudo apt update -y
sudo apt install nginx -y
ufw allow 'nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo /etc/init.d/nginx start
