#!/usr/bin/env bash
# Script to load balance between 2 servers
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y

echo "
frontend http
        bind *:80
        mode http
        default_backend my_backend

backend my_backend
        balance roundrobin
        mode http
        server 388216-web-01 54.160.81.105:80 check
        server 388216-web-02 34.227.90.3:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
