#!/usr/bin/env bash
# Script to replace port 8080 from image to port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
